version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.3
    - 2.38.4
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.2
    - 2.43.1
    - 2.45.0
  - dependency-name: "@11ty/eleventy"
    versions:
    - 0.12.1
  - dependency-name: "@11ty/eleventy-plugin-rss"
    versions:
    - 1.1.1
  - dependency-name: slugify
    versions:
    - 1.4.7
    - 1.5.0
  - dependency-name: "@11ty/eleventy-img"
    versions:
    - 0.8.2
  - dependency-name: stylelint
    versions:
    - 13.11.0
    - 13.12.0
  - dependency-name: "@11ty/eleventy-plugin-syntaxhighlight"
    versions:
    - 3.1.0
  - dependency-name: concurrently
    versions:
    - 6.0.0
